build: false

environment:
  matrix:
    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7.8"
      PYTHON_ARCH: "32"
      PYWIN_URL: "http://tcpdiag.dl.sourceforge.net/project/pywin32/pywin32/Build%20214/pywin32-214.win32-py2.7.exe"

init:
  - "PATH=C:\\Program Files\\PostgreSQL\\9.3\\bin\\;%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

install:
  - ps: (new-object net.webclient).DownloadFile($env:PYWIN_URL, 'C:/pywin32installer.exe')
  - "easy_install C:/pywin32installer.exe"
  - "pip install -r requirements-win.txt"
  - "pip install ."
  - "pip freeze"

test_script:
  - "behave"
